import "../globals.css";
import { Toaster } from "react-hot-toast";
import Link from "next/link";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`flex`}
      >
        <nav className="space-x-6 flex flex-col min-h-screen bg-amber-600 text-white ">
          <Link href="/dashboard">Dashboard</Link>
          <Link href="/profile">Profile</Link>
          <Link href="/">Home</Link>
        </nav>
        <Toaster/>
        {children}
      </body>
    </html>
  );
}
