import "../globals.css";
import { Toaster } from "react-hot-toast";
import Link from "next/link";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/authOptions";
import { redirect } from "next/navigation";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions);

  if (!session) return redirect("/login");
  if (session?.user?.role !== "admin") return redirect("/unauthorized");

  return (
    <html lang="en">
      <body className={`flex`}>
        <nav className="space-x-6 flex flex-col min-h-screen bg-amber-600 text-white ">
          <Link href="/dashboard">Dashboard</Link>
          <Link href="/profile">Profile</Link>
          <Link href="/">Home</Link>
        </nav>
        <Toaster />
        {children}
      </body>
    </html>
  );
}
