import "@/app/globals.css";
import DashboardLayout from "@/components/dashboard/DashboardLayout";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function DashboardMainLayout({ children }) {
  return <DashboardLayout>{children}</DashboardLayout>;
}
