import "@/app/globals.css";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/authOptions";
import DashboardLayout from "@/components/dashboard/DashboardLayout";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions);

  // if (!session) return redirect("/login");
  // if (session?.user?.role !== "admin") return redirect("/unauthorized");

  return (
    <html lang='en'>
      <body>
        <DashboardLayout>{children}</DashboardLayout>
      </body>
    </html>
  );
}
